/** Cloudflare Worker - Bulk DR Checker + SEO tools */
const VERSION="2026-09-19-seo-tools-v1",AHREFS_ENDPOINT="https://api.ahrefs.com/v3/public/domain-rating-free",MAX_DOMAINS=100,CONCURRENCY=5,FETCH_TIMEOUT_MS=30000,MAX_ATTEMPTS=3,RETRY_BASE_MS=1000,MAX_RETRY_MS=10000,RETRYABLE=new Set([429,500,502,503,504]),TOOL_SUBREQUEST_LIMIT=50,STATUS_MAX_URLS=10,META_MAX_URLS=8,DNS_MAX_QUERIES=40,DNS_TYPES=new Set(["A","AAAA","MX","TXT","NS"]);
function corsHeaders(request,env){const origin=request.headers.get("Origin"),allowedOrigin=env?.ALLOWED_ORIGIN;const headers={"Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type","Access-Control-Max-Age":"86400","Cache-Control":"no-store",Vary:"Origin"};if(allowedOrigin&&origin===allowedOrigin)headers["Access-Control-Allow-Origin"]=origin;return headers}\nfunction sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function normalizeDomain(value){if(typeof value!=="string")return null;let input=value.trim();if(!input)return null;try{if(!/^https?:\/\//i.test(input))input=`https://${input}`;let h=new URL(input).hostname.toLowerCase();if(h.endsWith("."))h=h.slice(0,-1);if(h.startsWith("www."))h=h.slice(4);return h}catch{return null}}
function isValidDomain(domain){if(!domain||domain.length>253)return false;const labels=domain.split(".");return labels.length>=2&&labels.every(l=>l.length>=1&&l.length<=63&&!l.startsWith("-")&&!l.endsWith("-")&&/^[a-zA-Z0-9-]+$/.test(l))}
function retryDelay(response,attempt){const n=Number(response.headers.get("Retry-After"));return Number.isFinite(n)&&n>=0?Math.min(n*1000,MAX_RETRY_MS):Math.min(RETRY_BASE_MS*2**(attempt-1),MAX_RETRY_MS)}
async function fetchWithRetry(url,options){let lastError,lastResponse;for(let attempt=1;attempt<=MAX_ATTEMPTS;attempt++){const c=new AbortController(),t=setTimeout(()=>c.abort(),FETCH_TIMEOUT_MS);try{const r=await fetch(url,{...options,signal:c.signal});lastResponse=r;if(!RETRYABLE.has(r.status)||attempt===MAX_ATTEMPTS)return r;await sleep(retryDelay(r,attempt))}catch(e){lastError=e;if(attempt===MAX_ATTEMPTS)throw e;await sleep(Math.min(RETRY_BASE_MS*2**(attempt-1),MAX_RETRY_MS))}finally{clearTimeout(t)}}if(lastResponse)return lastResponse;throw lastError||new Error("Request failed")}
function parseResult(domain,data){const rating=Number(data?.domain_rating?.domain_rating);return Number.isFinite(rating)?{domain,domain_rating:rating,status:"success"}:{domain,domain_rating:null,status:"not_found"}}
async function checkDomain(domain,apiKey){try{const u=new URL(AHREFS_ENDPOINT);u.searchParams.set("target",`https://${domain}`);u.searchParams.set("output","json");const r=await fetchWithRetry(u.toString(),{method:"GET",headers:{Authorization:`Bearer ${apiKey}`,Accept:"application/json"}}),d=await r.json().catch(()=>({}));if(!r.ok){let error="Ahrefs API request failed.";if(r.status===401)error="Ahrefs API authentication failed. Check AHREFS_API_KEY.";else if(r.status===403)error="Ahrefs API access was denied. Check your Ahrefs account/API permissions.";else if(r.status===429)error="Ahrefs API rate limit reached. Please try again later.";else if(r.status>=500)error="Ahrefs API is temporarily unavailable.";else if(d?.error?.message)error=`Ahrefs API: ${d.error.message}`;else if(d?.message)error=`Ahrefs API: ${d.message}`;return{domain,domain_rating:null,status:"failed",error}}return parseResult(domain,d)}catch(e){return{domain,domain_rating:null,status:"failed",error:e?.name==="AbortError"?"Ahrefs request timed out.":"Unable to connect to Ahrefs."}}
}
async function processDomains(domains,apiKey){const results=new Array(domains.length);let next=0;async function worker(){while(true){const i=next++;if(i>=domains.length)return;results[i]=await checkDomain(domains[i],apiKey)}}await Promise.all(Array.from({length:Math.min(CONCURRENCY,domains.length)},worker));return results}
async function checkAndIncrement(env,ip,name,limit){if(!env.RATE_LIMIT_KV)return{error:"RATE_LIMIT_KV is not configured."};const window=Math.floor(Date.now()/3600000),key=`ip:${name}:${ip}:${window}`,current=Number(await env.RATE_LIMIT_KV.get(key)||0);if(current>=limit)return{allowed:false};await env.RATE_LIMIT_KV.put(key,String(current+1),{expirationTtl:3700});return{allowed:true}}
const DR_PER_IP_LIMIT=10,DR_GLOBAL_DOMAIN_BUDGET=2000;\nasync function checkGlobalBudget(env,name,limit,amount){if(!env.RATE_LIMIT_KV)return{error:"RATE_LIMIT_KV is not configured."};const window=Math.floor(Date.now()/3600000),key="global:"+name+":"+window,current=Number((await env.RATE_LIMIT_KV.get(key))||0);if(current>=limit)return{allowed:false};await env.RATE_LIMIT_KV.put(key,String(current+amount),{expirationTtl:3700});return{allowed:true}}\nasync function enforceRateLimit(request,env,name,limit){const ip=request.headers.get("CF-Connecting-IP")||request.headers.get("X-Forwarded-For")?.split(",")[0]?.trim()||"unknown",r=await checkAndIncrement(env,ip,name,limit);if(r.error)return jsonResponse({success:false,error:r.error},500,request,env);if(!r.allowed)return jsonResponse({success:false,error:`Hourly limit reached for ${name}. Please wait for the next hourly window and try again.`},429,request,env);return null}

// --- SSRF protection ---
const BLOCKED_HOSTNAME_SUFFIXES=[".local",".localhost",".internal",".corp",".home.arpa"],BLOCKED_HOSTNAME_EXACT=new Set(["localhost"]);
function ipv4ToLong(p){return(parseInt(p[0],10)<<24)+(parseInt(p[1],10)<<16)+(parseInt(p[2],10)<<8)+parseInt(p[3],10)}
const BLOCKED_IPV4_RANGES=[["0.0.0.0",8],["10.0.0.0",8],["100.64.0.0",10],["127.0.0.0",8],["169.254.0.0",16],["172.16.0.0",12],["192.0.0.0",24],["192.0.2.0",24],["192.168.0.0",16],["198.18.0.0",15],["198.51.100.0",24],["203.0.113.0",24],["224.0.0.0",4],["240.0.0.0",4],["255.255.255.255",32]].map(([base,bits])=>{const b=ipv4ToLong(base.split(".")),mask=(~0<<(32-bits))>>>0;return{baseLong:b&mask,mask}})
function isIPv4Literal(h){return /^(\d{1,3}\.){3}\d{1,3}$/.test(h)}
function isBlockedIPv4(h){const p=h.split(".");if(p.length!==4||p.some(x=>Number(x)>255))return true;const n=ipv4ToLong(p)>>>0;return BLOCKED_IPV4_RANGES.some(({baseLong,mask})=>(n&mask)===baseLong)}
function isIPv6Literal(h){return h.includes(":")}
function isBlockedIPv6(h){const l=h.toLowerCase().replace(/^\[|\]$/g,"");if(l==="::1"||l==="::")return true;if(["fe8","fe9","fea","feb"].some(p=>l.startsWith(p)))return true;if(l.startsWith("fc")||l.startsWith("fd")||l.startsWith("2001:db8")||l.startsWith("ff"))return true;if(l.startsWith("::ffff:")){const e=l.split("::ffff:")[1];if(isIPv4Literal(e))return isBlockedIPv4(e)}return false}
function isBlockedHostnameString(h){const l=h.toLowerCase();return BLOCKED_HOSTNAME_EXACT.has(l)||BLOCKED_HOSTNAME_SUFFIXES.some(s=>l.endsWith(s))||(isIPv4Literal(l)?isBlockedIPv4(l):isIPv6Literal(l)?isBlockedIPv6(l):false)}
function createBudget(limit){let spent=0;return{spend(n){if(spent+n>limit)return false;spent+=n;return true},remaining(){return limit-spent}}}
async function isHostnameSafe(hostname,budget,resolvedCache){if(isBlockedHostnameString(hostname))return false;if(isIPv4Literal(hostname)||isIPv6Literal(hostname))return true;const key=hostname.toLowerCase();if(resolvedCache.has(key))return resolvedCache.get(key);for(const type of["A","AAAA"]){if(!budget.spend(1))return false;try{const r=await fetch(`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(hostname)}&type=${type}`,{headers:{Accept:"application/dns-json"}}),d=await r.json().catch(()=>null);for(const a of d?.Answer||[]){if((type==="A"&&isBlockedIPv4(a.data))||(type==="AAAA"&&isBlockedIPv6(a.data))){resolvedCache.set(key,false);return false}}}catch{resolvedCache.set(key,false);return false}}resolvedCache.set(key,true);return true}
async function ssrfSafeFetch(initialUrl,{method="GET",maxHops=3,timeoutMs=10000},budget,resolvedCache){let currentUrl=initialUrl;const chain=[];for(let hop=0;hop<=maxHops;hop++){let p;try{p=new URL(currentUrl)}catch{return{ok:false,error:"Invalid URL.",chain}}if(p.protocol!=="http:"&&p.protocol!=="https:")return{ok:false,error:"Only http/https URLs are allowed.",chain};const safe=await isHostnameSafe(p.hostname,budget,resolvedCache);if(!safe)return{ok:false,error:budget.remaining()===0?"Subrequest budget exceeded for this batch.":"This URL points to a blocked or private address.",chain,skipped:budget.remaining()===0};if(!budget.spend(1))return{ok:false,error:"Subrequest budget exceeded for this batch.",chain,skipped:true};const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);let response;try{response=await fetch(currentUrl,{method,redirect:"manual",signal:c.signal})}catch(e){clearTimeout(t);return{ok:false,error:e?.name==="AbortError"?"Request timed out.":"Could not connect.",chain}}clearTimeout(t);chain.push({url:currentUrl,status:response.status});if([301,302,303,307,308].includes(response.status)){const loc=response.headers.get("Location");try{response.body?.cancel()}catch{}if(!loc)return{ok:true,finalUrl:currentUrl,finalStatus:response.status,chain};currentUrl=new URL(loc,currentUrl).toString();continue}return{ok:true,finalUrl:currentUrl,finalStatus:response.status,chain,response}}return{ok:false,error:"Too many redirects.",chain}}
function normalizeToolUrl(value){if(typeof value!=="string"||!value.trim())return null;let input=value.trim();if(!/^[a-z][a-z0-9+.-]*:\/\//i.test(input))input=`https://${input}`;try{const u=new URL(input);return u.protocol==="http:"||u.protocol==="https:"?u.toString():input}catch{return null}}
function validateUrlBatch(body,max){if(!body||!Array.isArray(body.urls))return{error:"urls must be an array."};if(body.urls.length>max)return{error:`Maximum ${max} URLs are allowed per request. Please reduce the batch size.`};const urls=body.urls.map(normalizeToolUrl);if(urls.some(u=>!u))return{error:"Each URL must be a valid http/https URL or a bare domain."};return{urls}}
async function processPool(items,handler){const results=new Array(items.length);let next=0;async function worker(){while(true){const i=next++;if(i>=items.length)return;results[i]=await handler(items[i],i)}}await Promise.all(Array.from({length:Math.min(CONCURRENCY,items.length)},worker));return results}
async function handleCheckStatus(request,env){const limited=await enforceRateLimit(request,env,"status",15);if(limited)return limited;let body;try{body=await request.json()}catch{return jsonResponse({success:false,error:"Invalid JSON request."},400,request,env)}const v=validateUrlBatch(body,STATUS_MAX_URLS);if(v.error)return jsonResponse({success:false,error:v.error},400,request,env);const budget=createBudget(TOOL_SUBREQUEST_LIMIT),cache=new Map();const results=await processPool(v.urls,async url=>{if(budget.remaining()<=0)return{url,skipped:true,error:"Not processed — reduce batch size and try again."};const r=await ssrfSafeFetch(url,{method:"GET",maxHops:3},budget,cache);if(r.skipped)return{url,skipped:true,error:"Not processed — reduce batch size and try again.",chain:r.chain||[]};return{url,ok:r.ok,final_url:r.finalUrl||null,final_status:r.finalStatus||null,redirect_count:Math.max(0,(r.chain||[]).length-1),chain:r.chain||[],error:r.error||null}});return jsonResponse({success:true,results,subrequests_used:TOOL_SUBREQUEST_LIMIT-budget.remaining()},200,request,env)}
function getAttr(tag, name) { const re = new RegExp("\\b" + name + "\\s*=\\s*([\"'])([\\s\\S]*?)\\1", "i"); const m = tag.match(re); return m ? m[2].trim() : null; }
function firstMeta(html,pred){const tags=html.match(/<meta\b[^>]*>/gi)||[];for(const tag of tags)if(pred(tag))return getAttr(tag,"content")||"";return""}
function metaByName(html,name){return firstMeta(html,tag=>(getAttr(tag,"name")||"").toLowerCase()===name.toLowerCase())}
function metaByProperty(html,p){return firstMeta(html,tag=>(getAttr(tag,"property")||"").toLowerCase()===p.toLowerCase())}
function firstLinkCanonical(html){const tags=html.match(/<link\b[^>]*>/gi)||[];for(const tag of tags){const rel=(getAttr(tag,"rel")||"").toLowerCase().split(/\s+/);if(rel.includes("canonical"))return getAttr(tag,"href")||""}return""}
function htmlTitle(html){return(html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"").replace(/\s+/g," ").trim()}
async function readBodyCap(response,maxBytes){const reader=response.body?.getReader();if(!reader)return await response.text().catch(()=>"" );const decoder=new TextDecoder();let received=0,result="";try{while(true){const{done,value}=await reader.read();if(done)break;received+=value.length;result+=decoder.decode(value,{stream:true});if(received>=maxBytes){await reader.cancel().catch(()=>{});break}}}catch{}return result}\nfunction decodeBasicEntities(v){return String(v||"").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">")}
async function handleCheckMeta(request,env){const limited=await enforceRateLimit(request,env,"meta",15);if(limited)return limited;let body;try{body=await request.json()}catch{return jsonResponse({success:false,error:"Invalid JSON request."},400,request,env)}const v=validateUrlBatch(body,META_MAX_URLS);if(v.error)return jsonResponse({success:false,error:v.error},400,request,env);const budget=createBudget(TOOL_SUBREQUEST_LIMIT),cache=new Map();const results=await processPool(v.urls,async url=>{if(budget.remaining()<=0)return{url,skipped:true,error:"Not processed — reduce batch size and try again."};const r=await ssrfSafeFetch(url,{method:"GET",maxHops:3},budget,cache);if(r.skipped)return{url,skipped:true,error:"Not processed — reduce batch size and try again.",chain:r.chain||[]};if(!r.ok||!r.response)return{url,final_url:r.finalUrl||null,title:"",description:"",canonical:"",og:{title:"",description:"",image:"",type:""},twitter:{card:"",title:"",description:"",image:""},robots:"",h1_count:0,error:r.error||"Unable to fetch page."};const html=await readBodyCap(r.response,300*1024);return{url,final_url:r.finalUrl,title:decodeBasicEntities(htmlTitle(html)),description:decodeBasicEntities(metaByName(html,"description")),canonical:decodeBasicEntities(firstLinkCanonical(html)),og:{title:decodeBasicEntities(metaByProperty(html,"og:title")),description:decodeBasicEntities(metaByProperty(html,"og:description")),image:decodeBasicEntities(metaByProperty(html,"og:image")),type:decodeBasicEntities(metaByProperty(html,"og:type"))},twitter:{card:decodeBasicEntities(metaByName(html,"twitter:card")),title:decodeBasicEntities(metaByName(html,"twitter:title")),description:decodeBasicEntities(metaByName(html,"twitter:description")),image:decodeBasicEntities(metaByName(html,"twitter:image")),},robots:decodeBasicEntities(metaByName(html,"robots")),h1_count:(html.match(/<h1[\\s>]/gi)||[]).length,error:null}});return jsonResponse({success:true,results,subrequests_used:TOOL_SUBREQUEST_LIMIT-budget.remaining()},200,request,env)}
async function handleDnsLookup(request,env){const limited=await enforceRateLimit(request,env,"dns",20);if(limited)return limited;let body;try{body=await request.json()}catch{return jsonResponse({success:false,error:"Invalid JSON request."},400,request,env)}if(!body||!Array.isArray(body.domains)||!Array.isArray(body.types))return jsonResponse({success:false,error:"domains and types must be arrays."},400,request,env);if(!body.domains.length)return jsonResponse({success:false,error:"Please provide at least one domain."},400,request,env);if(!body.types.length)return jsonResponse({success:false,error:"Please provide at least one DNS record type."},400,request,env);const types=[...new Set(body.types.map(t=>String(t).toUpperCase()))],bad=types.filter(t=>!DNS_TYPES.has(t));if(bad.length)return jsonResponse({success:false,error:`Unsupported DNS record type(s): ${bad.join(", ")}. Allowed types: A, AAAA, MX, TXT, NS. ANY is not supported.`},400,request,env);if(body.domains.length*types.length>DNS_MAX_QUERIES)return jsonResponse({success:false,error:`Maximum ${DNS_MAX_QUERIES} domain/type lookups per request. Check fewer domains or fewer record types per request.`},400,request,env);const domains=[];for(const raw of body.domains){const d=normalizeDomain(raw);if(!d||!isValidDomain(d))return jsonResponse({success:false,error:`Invalid domain: ${String(raw)}`},400,request,env);domains.push(d)}const unique=[...new Set(domains)],budget=createBudget(TOOL_SUBREQUEST_LIMIT),results=unique.map(domain=>({domain,records:Object.fromEntries(types.map(t=>[t,[]])),error:null})),jobs=[];unique.forEach((domain,di)=>types.forEach(type=>jobs.push({domain,di,type})));await processPool(jobs,async job=>{if(!budget.spend(1)){results[job.di].error="Not processed — reduce batch size and try again.";return}try{const r=await fetch(`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(job.domain)}&type=${job.type}`,{headers:{Accept:"application/dns-json"}}),d=await r.json().catch(()=>null);if(!r.ok){results[job.di].error=results[job.di].error||`DNS lookup failed for ${job.type}.`;return}results[job.di].records[job.type]=(d?.Answer||[]).map(a=>a.data).filter(Boolean)}catch{results[job.di].error=results[job.di].error||`DNS lookup failed for ${job.type}.`}});return jsonResponse({success:true,results,subrequests_used:TOOL_SUBREQUEST_LIMIT-budget.remaining()},200,request,env)}
async function handleCheck(request,env){if(!env.AHREFS_API_KEY)return jsonResponse({success:false,error:"AHREFS_API_KEY is not configured in Cloudflare Workers.",version:VERSION},500,request,env);const limited=await enforceRateLimit(request,env,"dr",DR_PER_IP_LIMIT);if(limited)return limited;let body;try{body=await request.json()}catch{return jsonResponse({success:false,error:"Invalid JSON request.",version:VERSION},400,request,env)}if(!body||!Array.isArray(body.domains))return jsonResponse({success:false,error:"domains must be an array.",version:VERSION},400,request,env);if(body.domains.length>MAX_DOMAINS)return jsonResponse({success:false,error:`Maximum ${MAX_DOMAINS} domains are allowed.`,version:VERSION},400,request,env);const invalidDomains=[],validDomains=[];for(const item of body.domains){const domain=normalizeDomain(item);if(!domain||!isValidDomain(domain))invalidDomains.push(typeof item==="string"?item:String(item));else validDomains.push(domain)}const domains=[...new Set(validDomains)];if(!domains.length)return jsonResponse({success:false,error:"No valid domains were provided.",invalid_domains:invalidDomains,version:VERSION},400,request,env);const globalCheck=await checkGlobalBudget(env,"dr",DR_GLOBAL_DOMAIN_BUDGET,domains.length);if(globalCheck.error)return jsonResponse({success:false,error:globalCheck.error,version:VERSION},500,request,env);if(!globalCheck.allowed)return jsonResponse({success:false,error:"This tool has hit its shared usage limit for the hour. Please try again later.",version:VERSION},429,request,env);const results=await processDomains(domains,env.AHREFS_API_KEY);return jsonResponse({success:true,results,invalid_domains:invalidDomains,version:VERSION},200,request,env)}
export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders(request,env)});const url=new URL(request.url);if(url.pathname==="/health"&&request.method==="GET")return jsonResponse({ok:true,service:"bulk-dr-checker",version:VERSION,endpoints:{health:"/health",check:"/check-dr",status:"/check-status",meta:"/check-meta",dns:"/dns-lookup"}},200,request,env);if(url.pathname==="/"&&request.method==="GET")return jsonResponse({ok:true,service:"bulk-dr-checker",version:VERSION,endpoints:{health:"/health",check:"/check-dr",status:"/check-status",meta:"/check-meta",dns:"/dns-lookup"}},200,request,env);if(url.pathname==="/check-dr"&&request.method==="POST")return handleCheck(request,env);if(url.pathname==="/check-status"&&request.method==="POST")return handleCheckStatus(request,env);if(url.pathname==="/check-meta"&&request.method==="POST")return handleCheckMeta(request,env);if(url.pathname==="/dns-lookup"&&request.method==="POST")return handleDnsLookup(request,env);return jsonResponse({success:false,error:"Not Found",version:VERSION},404,request,env)}};function jsonResponse(data,status=200,request,env){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","X-Content-Type-Options":"nosniff",...corsHeaders(request,env)}})}\nfunction sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function normalizeDomain(value){if(typeof value!=="string")return null;let input=value.trim();if(!input)return null;try{if(!/^https?:\/\//i.test(input))input=`https://${input}`;let h=new URL(input).hostname.toLowerCase();if(h.endsWith("."))h=h.slice(0,-1);if(h.startsWith("www."))h=h.slice(4);return h}catch{return null}}
function isValidDomain(domain){if(!domain||domain.length>253)return false;const labels=domain.split(".");return labels.length>=2&&labels.every(l=>l.length>=1&&l.length<=63&&!l.startsWith("-")&&!l.endsWith("-")&&/^[a-zA-Z0-9-]+$/.test(l))}
function retryDelay(response,attempt){const n=Number(response.headers.get("Retry-After"));return Number.isFinite(n)&&n>=0?Math.min(n*1000,MAX_RETRY_MS):Math.min(RETRY_BASE_MS*2**(attempt-1),MAX_RETRY_MS)}
async function fetchWithRetry(url,options){let lastError,lastResponse;for(let attempt=1;attempt<=MAX_ATTEMPTS;attempt++){const c=new AbortController(),t=setTimeout(()=>c.abort(),FETCH_TIMEOUT_MS);try{const r=await fetch(url,{...options,signal:c.signal});lastResponse=r;if(!RETRYABLE.has(r.status)||attempt===MAX_ATTEMPTS)return r;await sleep(retryDelay(r,attempt))}catch(e){lastError=e;if(attempt===MAX_ATTEMPTS)throw e;await sleep(Math.min(RETRY_BASE_MS*2**(attempt-1),MAX_RETRY_MS))}finally{clearTimeout(t)}}if(lastResponse)return lastResponse;throw lastError||new Error("Request failed")}
function parseResult(domain,data){const rating=Number(data?.domain_rating?.domain_rating);return Number.isFinite(rating)?{domain,domain_rating:rating,status:"success"}:{domain,domain_rating:null,status:"not_found"}}
async function checkDomain(domain,apiKey){try{const u=new URL(AHREFS_ENDPOINT);u.searchParams.set("target",`https://${domain}`);u.searchParams.set("output","json");const r=await fetchWithRetry(u.toString(),{method:"GET",headers:{Authorization:`Bearer ${apiKey}`,Accept:"application/json"}}),d=await r.json().catch(()=>({}));if(!r.ok){let error="Ahrefs API request failed.";if(r.status===401)error="Ahrefs API authentication failed. Check AHREFS_API_KEY.";else if(r.status===403)error="Ahrefs API access was denied. Check your Ahrefs account/API permissions.";else if(r.status===429)error="Ahrefs API rate limit reached. Please try again later.";else if(r.status>=500)error="Ahrefs API is temporarily unavailable.";else if(d?.error?.message)error=`Ahrefs API: ${d.error.message}`;else if(d?.message)error=`Ahrefs API: ${d.message}`;return{domain,domain_rating:null,status:"failed",error}}return parseResult(domain,d)}catch(e){return{domain,domain_rating:null,status:"failed",error:e?.name==="AbortError"?"Ahrefs request timed out.":"Unable to connect to Ahrefs."}}
}
async function processDomains(domains,apiKey){const results=new Array(domains.length);let next=0;async function worker(){while(true){const i=next++;if(i>=domains.length)return;results[i]=await checkDomain(domains[i],apiKey)}}await Promise.all(Array.from({length:Math.min(CONCURRENCY,domains.length)},worker));return results}
async function checkAndIncrement(env,ip,name,limit){if(!env.RATE_LIMIT_KV)return{error:"RATE_LIMIT_KV is not configured."};const window=Math.floor(Date.now()/3600000),key=`ip:${name}:${ip}:${window}`,current=Number(await env.RATE_LIMIT_KV.get(key)||0);if(current>=limit)return{allowed:false};await env.RATE_LIMIT_KV.put(key,String(current+1),{expirationTtl:3700});return{allowed:true}}
async function enforceRateLimit(request,env,name,limit){const ip=request.headers.get("CF-Connecting-IP")||request.headers.get("X-Forwarded-For")?.split(",")[0]?.trim()||"unknown",r=await checkAndIncrement(env,ip,name,limit);if(r.error)return jsonResponse({success:false,error:r.error},500,request,env);if(!r.allowed)return jsonResponse({success:false,error:`Hourly limit reached for ${name}. Please wait for the next hourly window and try again.`},429,request,env);return null}

// --- SSRF protection ---
const BLOCKED_HOSTNAME_SUFFIXES=[".local",".localhost",".internal",".corp",".home.arpa"],BLOCKED_HOSTNAME_EXACT=new Set(["localhost"]);
function ipv4ToLong(p){return(parseInt(p[0],10)<<24)+(parseInt(p[1],10)<<16)+(parseInt(p[2],10)<<8)+parseInt(p[3],10)}
const BLOCKED_IPV4_RANGES=[["0.0.0.0",8],["10.0.0.0",8],["100.64.0.0",10],["127.0.0.0",8],["169.254.0.0",16],["172.16.0.0",12],["192.0.0.0",24],["192.0.2.0",24],["192.168.0.0",16],["198.18.0.0",15],["198.51.100.0",24],["203.0.113.0",24],["224.0.0.0",4],["240.0.0.0",4],["255.255.255.255",32]].map(([base,bits])=>{const b=ipv4ToLong(base.split(".")),mask=(~0<<(32-bits))>>>0;return{baseLong:b&mask,mask}})
function isIPv4Literal(h){return /^(\d{1,3}\.){3}\d{1,3}$/.test(h)}
function isBlockedIPv4(h){const p=h.split(".");if(p.length!==4||p.some(x=>Number(x)>255))return true;const n=ipv4ToLong(p)>>>0;return BLOCKED_IPV4_RANGES.some(({baseLong,mask})=>(n&mask)===baseLong)}
function isIPv6Literal(h){return h.includes(":")}
function isBlockedIPv6(h){const l=h.toLowerCase().replace(/^\[|\]$/g,"");if(l==="::1"||l==="::")return true;if(["fe8","fe9","fea","feb"].some(p=>l.startsWith(p)))return true;if(l.startsWith("fc")||l.startsWith("fd")||l.startsWith("2001:db8")||l.startsWith("ff"))return true;if(l.startsWith("::ffff:")){const e=l.split("::ffff:")[1];if(isIPv4Literal(e))return isBlockedIPv4(e)}return false}
function isBlockedHostnameString(h){const l=h.toLowerCase();return BLOCKED_HOSTNAME_EXACT.has(l)||BLOCKED_HOSTNAME_SUFFIXES.some(s=>l.endsWith(s))||(isIPv4Literal(l)?isBlockedIPv4(l):isIPv6Literal(l)?isBlockedIPv6(l):false)}
function createBudget(limit){let spent=0;return{spend(n){if(spent+n>limit)return false;spent+=n;return true},remaining(){return limit-spent}}}
async function isHostnameSafe(hostname,budget,resolvedCache){if(isBlockedHostnameString(hostname))return false;if(isIPv4Literal(hostname)||isIPv6Literal(hostname))return true;const key=hostname.toLowerCase();if(resolvedCache.has(key))return resolvedCache.get(key);for(const type of["A","AAAA"]){if(!budget.spend(1))return false;try{const r=await fetch(`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(hostname)}&type=${type}`,{headers:{Accept:"application/dns-json"}}),d=await r.json().catch(()=>null);for(const a of d?.Answer||[]){if((type==="A"&&isBlockedIPv4(a.data))||(type==="AAAA"&&isBlockedIPv6(a.data))){resolvedCache.set(key,false);return false}}}catch{resolvedCache.set(key,false);return false}}resolvedCache.set(key,true);return true}
async function ssrfSafeFetch(initialUrl,{method="GET",maxHops=3,timeoutMs=10000},budget,resolvedCache){let currentUrl=initialUrl;const chain=[];for(let hop=0;hop<=maxHops;hop++){let p;try{p=new URL(currentUrl)}catch{return{ok:false,error:"Invalid URL.",chain}}if(p.protocol!=="http:"&&p.protocol!=="https:")return{ok:false,error:"Only http/https URLs are allowed.",chain};const safe=await isHostnameSafe(p.hostname,budget,resolvedCache);if(!safe)return{ok:false,error:budget.remaining()===0?"Subrequest budget exceeded for this batch.":"This URL points to a blocked or private address.",chain,skipped:budget.remaining()===0};if(!budget.spend(1))return{ok:false,error:"Subrequest budget exceeded for this batch.",chain,skipped:true};const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);let response;try{response=await fetch(currentUrl,{method,redirect:"manual",signal:c.signal})}catch(e){clearTimeout(t);return{ok:false,error:e?.name==="AbortError"?"Request timed out.":"Could not connect.",chain}}clearTimeout(t);chain.push({url:currentUrl,status:response.status});if([301,302,303,307,308].includes(response.status)){const loc=response.headers.get("Location");try{response.body?.cancel()}catch{}if(!loc)return{ok:true,finalUrl:currentUrl,finalStatus:response.status,chain};currentUrl=new URL(loc,currentUrl).toString();continue}return{ok:true,finalUrl:currentUrl,finalStatus:response.status,chain,response}}return{ok:false,error:"Too many redirects.",chain}}
function normalizeToolUrl(value){if(typeof value!=="string"||!value.trim())return null;let input=value.trim();if(!/^[a-z][a-z0-9+.-]*:\/\//i.test(input))input=`https://${input}`;try{const u=new URL(input);return u.protocol==="http:"||u.protocol==="https:"?u.toString():input}catch{return null}}
function validateUrlBatch(body,max){if(!body||!Array.isArray(body.urls))return{error:"urls must be an array."};if(body.urls.length>max)return{error:`Maximum ${max} URLs are allowed per request. Please reduce the batch size.`};const urls=body.urls.map(normalizeToolUrl);if(urls.some(u=>!u))return{error:"Each URL must be a valid http/https URL or a bare domain."};return{urls}}
async function processPool(items,handler){const results=new Array(items.length);let next=0;async function worker(){while(true){const i=next++;if(i>=items.length)return;results[i]=await handler(items[i],i)}}await Promise.all(Array.from({length:Math.min(CONCURRENCY,items.length)},worker));return results}
async function handleCheckStatus(request,env){const limited=await enforceRateLimit(request,env,"status",15);if(limited)return limited;let body;try{body=await request.json()}catch{return jsonResponse({success:false,error:"Invalid JSON request."},400,request,env)}const v=validateUrlBatch(body,STATUS_MAX_URLS);if(v.error)return jsonResponse({success:false,error:v.error},400,request,env);const budget=createBudget(TOOL_SUBREQUEST_LIMIT),cache=new Map();const results=await processPool(v.urls,async url=>{if(budget.remaining()<=0)return{url,skipped:true,error:"Not processed — reduce batch size and try again."};const r=await ssrfSafeFetch(url,{method:"GET",maxHops:3},budget,cache);if(r.skipped)return{url,skipped:true,error:"Not processed — reduce batch size and try again.",chain:r.chain||[]};return{url,ok:r.ok,final_url:r.finalUrl||null,final_status:r.finalStatus||null,redirect_count:Math.max(0,(r.chain||[]).length-1),chain:r.chain||[],error:r.error||null}});return jsonResponse({success:true,results,subrequests_used:TOOL_SUBREQUEST_LIMIT-budget.remaining()},200,request,env)}
function getAttr(tag,name){const re=new RegExp(`\b${name}\s*=\s*(["'])([\s\S]*?)\1`,"i"),m=tag.match(re);return m?m[2].trim():null}
function firstMeta(html,pred){const tags=html.match(/<meta\b[^>]*>/gi)||[];for(const tag of tags)if(pred(tag))return getAttr(tag,"content")||"";return""}
function metaByName(html,name){return firstMeta(html,tag=>(getAttr(tag,"name")||"").toLowerCase()===name.toLowerCase())}
function metaByProperty(html,p){return firstMeta(html,tag=>(getAttr(tag,"property")||"").toLowerCase()===p.toLowerCase())}
function firstLinkCanonical(html){const tags=html.match(/<link\b[^>]*>/gi)||[];for(const tag of tags){const rel=(getAttr(tag,"rel")||"").toLowerCase().split(/\s+/);if(rel.includes("canonical"))return getAttr(tag,"href")||""}return""}
function htmlTitle(html){return(html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"").replace(/\s+/g," ").trim()}
function decodeBasicEntities(v){return String(v||"").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">")}
async function handleCheckMeta(request,env){const limited=await enforceRateLimit(request,env,"meta",15);if(limited)return limited;let body;try{body=await request.json()}catch{return jsonResponse({success:false,error:"Invalid JSON request."},400,request,env)}const v=validateUrlBatch(body,META_MAX_URLS);if(v.error)return jsonResponse({success:false,error:v.error},400,request,env);const budget=createBudget(TOOL_SUBREQUEST_LIMIT),cache=new Map();const results=await processPool(v.urls,async url=>{if(budget.remaining()<=0)return{url,skipped:true,error:"Not processed — reduce batch size and try again."};const r=await ssrfSafeFetch(url,{method:"GET",maxHops:3},budget,cache);if(r.skipped)return{url,skipped:true,error:"Not processed — reduce batch size and try again.",chain:r.chain||[]};if(!r.ok||!r.response)return{url,final_url:r.finalUrl||null,title:"",description:"",canonical:"",og:{title:"",description:"",image:"",type:""},twitter:{card:"",title:"",description:"",image:""},robots:"",h1_count:0,error:r.error||"Unable to fetch page."};const html=await readBodyCap(r.response,300*1024);return{url,final_url:r.finalUrl,title:decodeBasicEntities(htmlTitle(html)),description:decodeBasicEntities(metaByName(html,"description")),canonical:decodeBasicEntities(firstLinkCanonical(html)),og:{title:decodeBasicEntities(metaByProperty(html,"og:title")),description:decodeBasicEntities(metaByProperty(html,"og:description")),image:decodeBasicEntities(metaByProperty(html,"og:image")),type:decodeBasicEntities(metaByProperty(html,"og:type"))},twitter:{card:decodeBasicEntities(metaByName(html,"twitter:card")),title:decodeBasicEntities(metaByName(html,"twitter:title")),description:decodeBasicEntities(metaByName(html,"twitter:description")),image:decodeBasicEntities(metaByName(html,"twitter:image")),},robots:decodeBasicEntities(metaByName(html,"robots")),h1_count:(html.match(/<h1[\\s>]/gi)||[]).length,error:null}});return jsonResponse({success:true,results,subrequests_used:TOOL_SUBREQUEST_LIMIT-budget.remaining()},200,request,env)}
async function handleDnsLookup(request,env){const limited=await enforceRateLimit(request,env,"dns",20);if(limited)return limited;let body;try{body=await request.json()}catch{return jsonResponse({success:false,error:"Invalid JSON request."},400,request,env)}if(!body||!Array.isArray(body.domains)||!Array.isArray(body.types))return jsonResponse({success:false,error:"domains and types must be arrays."},400,request,env);if(!body.domains.length)return jsonResponse({success:false,error:"Please provide at least one domain."},400,request,env);if(!body.types.length)return jsonResponse({success:false,error:"Please provide at least one DNS record type."},400,request,env);const types=[...new Set(body.types.map(t=>String(t).toUpperCase()))],bad=types.filter(t=>!DNS_TYPES.has(t));if(bad.length)return jsonResponse({success:false,error:`Unsupported DNS record type(s): ${bad.join(", ")}. Allowed types: A, AAAA, MX, TXT, NS. ANY is not supported.`},400,request,env);if(body.domains.length*types.length>DNS_MAX_QUERIES)return jsonResponse({success:false,error:`Maximum ${DNS_MAX_QUERIES} domain/type lookups per request. Check fewer domains or fewer record types per request.`},400,request,env);const domains=[];for(const raw of body.domains){const d=normalizeDomain(raw);if(!d||!isValidDomain(d))return jsonResponse({success:false,error:`Invalid domain: ${String(raw)}`},400,request,env);domains.push(d)}const unique=[...new Set(domains)],budget=createBudget(TOOL_SUBREQUEST_LIMIT),results=unique.map(domain=>({domain,records:Object.fromEntries(types.map(t=>[t,[]])),error:null})),jobs=[];unique.forEach((domain,di)=>types.forEach(type=>jobs.push({domain,di,type})));await processPool(jobs,async job=>{if(!budget.spend(1)){results[job.di].error="Not processed — reduce batch size and try again.";return}try{const r=await fetch(`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(job.domain)}&type=${job.type}`,{headers:{Accept:"application/dns-json"}}),d=await r.json().catch(()=>null);if(!r.ok){results[job.di].error=results[job.di].error||`DNS lookup failed for ${job.type}.`;return}results[job.di].records[job.type]=(d?.Answer||[]).map(a=>a.data).filter(Boolean)}catch{results[job.di].error=results[job.di].error||`DNS lookup failed for ${job.type}.`}});return jsonResponse({success:true,results,subrequests_used:TOOL_SUBREQUEST_LIMIT-budget.remaining()},200,request,env)}
async function handleCheck(request,env){if(!env.AHREFS_API_KEY)return jsonResponse({success:false,error:"AHREFS_API_KEY is not configured in Cloudflare Workers.",version:VERSION},500,request,env);let body;try{body=await request.json()}catch{return jsonResponse({success:false,error:"Invalid JSON request.",version:VERSION},400,request,env)}if(!body||!Array.isArray(body.domains))return jsonResponse({success:false,error:"domains must be an array.",version:VERSION},400,request,env);if(body.domains.length>MAX_DOMAINS)return jsonResponse({success:false,error:`Maximum ${MAX_DOMAINS} domains are allowed.`,version:VERSION},400,request,env);const invalidDomains=[],validDomains=[];for(const item of body.domains){const domain=normalizeDomain(item);if(!domain||!isValidDomain(domain))invalidDomains.push(typeof item==="string"?item:String(item));else validDomains.push(domain)}const domains=[...new Set(validDomains)];if(!domains.length)return jsonResponse({success:false,error:"No valid domains were provided.",invalid_domains:invalidDomains,version:VERSION},400,request,env);const results=await processDomains(domains,env.AHREFS_API_KEY);return jsonResponse({success:true,results,invalid_domains:invalidDomains,version:VERSION},200,request,env)}
export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders(request,env)});const url=new URL(request.url);if(url.pathname==="/health"&&request.method==="GET")return jsonResponse({ok:true,service:"bulk-dr-checker",version:VERSION,corsOrigin:env?.ALLOWED_ORIGIN||"*",ahrefsConfigured:Boolean(env.AHREFS_API_KEY),endpoints:{health:"/health",check:"/check-dr",status:"/check-status",meta:"/check-meta",dns:"/dns-lookup"}},200,request,env);if(url.pathname==="/"&&request.method==="GET")return jsonResponse({ok:true,service:"bulk-dr-checker",version:VERSION,endpoints:{health:"/health",check:"/check-dr",status:"/check-status",meta:"/check-meta",dns:"/dns-lookup"}},200,request,env);if(url.pathname==="/check-dr"&&request.method==="POST")return handleCheck(request,env);if(url.pathname==="/check-status"&&request.method==="POST")return handleCheckStatus(request,env);if(url.pathname==="/check-meta"&&request.method==="POST")return handleCheckMeta(request,env);if(url.pathname==="/dns-lookup"&&request.method==="POST")return handleDnsLookup(request,env);return jsonResponse({success:false,error:"Not Found",version:VERSION},404,request,env)}};
