const textEl=document.getElementById("readText"),keywordEl=document.getElementById("readKeyword"),resultsEl=document.getElementById("readResults");
const STOPWORDS=new Set("a an and are as at be been being but by can could did do does for from had has have he her here him his how i if in into is it its just me more most my no not of on one or our out she should so some than that the their them then there these they this to too was we were what when where which who will with would you your".split(" "));
function countSyllables(word){word=word.toLowerCase().replace(/[^a-z]/g,"");if(!word)return 0;if(word.length<=3)return 1;if(/[^aeiouy]e$/.test(word)&&!/[^aeiouy]le$/.test(word))word=word.slice(0,-1);const matches=word.match(/[aeiouy]{1,2}/g);return Math.max(1,matches?matches.length:1)}
function esc(s){return String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function words(text){return text.match(/[A-Za-z0-9]+(?:['’-][A-Za-z0-9]+)*/g)||[]}
function sentences(text){return text.split(/[.!?]+(?:["'”’)]*)?(?=\s|$)/).map(x=>x.trim()).filter(Boolean)}
function paragraphs(text){return text.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean)}
function gradeFromAri(ari){return ari<=1?1:Math.max(1,Math.min(18,Math.ceil(ari)))}
function keywordCount(text,phrase){if(!phrase.trim())return 0;const escaped=phrase.trim().replace(/[.*+?^\$\{\}()|[\]\\]/g,"\\$&");const re=new RegExp("(?<![A-Za-z0-9])"+escaped+"(?![A-Za-z0-9])","gi");return (text.match(re)||[]).length}
function topKeywords(ws){const counts=new Map();for(const w of ws){const k=w.toLowerCase();if(k.length<3||STOPWORDS.has(k))continue;counts.set(k,(counts.get(k)||0)+1)}return [...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,10)}
function render(){const text=textEl.value.trim();if(!text){resultsEl.innerHTML='<div class="empty-state">Start typing or paste text to see live readability metrics.</div>';return}const ws=words(text),ss=sentences(text),ps=paragraphs(text),wc=ws.length,sc=ss.length||1,chars=(text.match(/[A-Za-z0-9]/g)||[]).length,syl=ws.reduce((n,w)=>n+countSyllables(w),0),avg=wc/sc,ari=4.71*(chars/(wc||1))+0.5*(wc/sc)-21.43,re=206.835-1.015*(wc/sc)-84.6*(syl/(wc||1)),fk=0.39*(wc/sc)+11.8*(syl/(wc||1))-15.59,kw=keywordEl.value.trim(),kcount=keywordCount(text,kw),density=wc?kcount/wc*100:0,top=topKeywords(ws);resultsEl.innerHTML='<div class="read-summary"><div><span>Words</span><strong>'+wc+'</strong></div><div><span>Sentences</span><strong>'+ss.length+'</strong></div><div><span>Paragraphs</span><strong>'+ps.length+'</strong></div><div><span>Avg words / sentence</span><strong>'+avg.toFixed(1)+'</strong></div><div class="primary"><span>ARI grade</span><strong>'+gradeFromAri(ari)+'</strong><small>ARI '+ari.toFixed(1)+'</small></div><div><span>Reading Ease</span><strong>'+re.toFixed(1)+'</strong></div><div><span>FK Grade</span><strong>'+fk.toFixed(1)+'</strong></div></div><div class="read-detail"><div><h3>Keyword</h3><p>'+(kw?esc(kcount+" occurrence"+(kcount===1?"":"s")+" · "+density.toFixed(2)+"% of words"):"Enter a target keyword or phrase for density.")+'</p></div><div><h3>Top 10 keywords</h3><ol>'+top.map(([k,n])=>'<li><code>'+esc(k)+'</code><span>'+n+'</span></li>').join("")+'</ol></div></div>'}
let timer;function update(){clearTimeout(timer);timer=setTimeout(render,300)}textEl.addEventListener("input",update);keywordEl.addEventListener("input",update);render();